### ISSUE TITLE
Importing flask.ext.cacheify is deprecated

### ISSUE THREAD

**Issue by rkuykendall** [rdegges/flask-heroku-cacheify#13]
First thing, thank you for an amazing library! It was so easy to set up, I just followed the instructions, ran it once, and it worked! Just reporting a few warnings I'm getting:

```
/app/.heroku/python/lib/python3.6/site-packages/flask/exthook.py:71: ExtDeprecationWarning: Importing flask.ext.cacheify is deprecated, use flask_cacheify instead.
```
I made that change in my app, and then got
```
/home/rkuykendall/.local/lib/python3.6/site-packages/flask/exthook.py:71: ExtDeprecationWarning: Importing flask.ext.cache is deprecated, use flask_cache instead.
```
Everything is working, but I thought you would want to know.

**Comment by rdegges** [comment]
Just updated this! Thanks! I updated the docs and pushed a new release to PyPI.
