### ISSUE TITLE
Does Not Work With Redis To Go

### ISSUE THREAD

**Issue by peoplecallmefrancois** [rdegges/flask-heroku-cacheify#5]
Unfortunately, the server just hangs whenever I use a cached view with Redis To Go.

It works with Memcachier though.

Do you know why it may not be working with Redis To Go?

I've heard Redis is better than Memecache that's why I was hoping to use Redis To Go (since it's the only free Redis option available).

P.S. This is a great library, it saved me time trying to figure out how to set the cache up on Heroku, so thank you!

**Comment by rdegges** [comment]
Hmm, working for me. Closing this unless someone else has an issue.
